### ISSUE TITLE
Dynamic service discovery with Consul and Registrator

### ISSUE THREAD

**Issue by xiecancn** [TjWallas/dynamic-netsec#34]
We can use **consul** and **Registrator** to automatically discover and register services (containers with port exposed), however Registrator uses the host IP as service IP (an explanation is [here](https://github.com/bryanlarsen/registrator/commit/0182dd4bdb4cc6b98aa2b80103fd591f65132f46) ), isn't it contradictory to our previous design, since we are using OVS instead of docker networks? @TjWallas

**Comment by TjWallas** [comment]
@xiecancn Good question. Apparently, there is a hidden feature which allows you to use the IP address from a docker label ;)

Take a look here:
* https://github.com/gliderlabs/registrator/issues/454
* https://github.com/gliderlabs/registrator/pull/480

**Comment by TjWallas** [comment]
@xiecancn Is this one clear? You simply add a label to you docker container using the docker cli, and then you can use the registrator with the option `useIpFromLabel=<label_name>`

**Comment by xiecancn** [comment]
yes, now when creating containers, a label with service IP will be added. registrator detects the containers and register them (with user defined service IP) automatically on the consul service catalog.
`$ curl localhost:8500/v1/catalog/service/nginx`
```json
{
   "ID":"805806cc-75dc-a15f-9ccc-15f5bc87c63f",
   "Node":"minor1",
   "Address":"192.168.0.2",
   "Datacenter":"dc1",
   "TaggedAddresses":{
      "lan":"192.168.0.2",
      "wan":"192.168.0.2"
   },
   "NodeMeta":{
      "consul-network-segment":""
   },
   "ServiceID":"minor1:container1:80",
   "ServiceName":"nginx",
   "ServiceTags":[

   ],
   "ServiceAddress":"173.16.1.11",
   "ServiceMeta":{

   },
   "ServicePort":32768,
   "ServiceEnableTagOverride":false,
   "CreateIndex":81,
   "ModifyIndex":81
}

```

**Comment by xiecancn** [comment]
@TjWallas I may be wrong , but it seems that if we want to use the exposed ports, we have to map the container ports to the host ports. In this way, docker will use the default network instead of using OVS. If we don't publish ports directly, Registrator will simply ignore the containers.

Using  [openvswitch driver](http://docs.openvswitch.org/en/latest/howto/docker/) seems to be a solution. however in this way most works that has done before must be modified. Do you have any suggestions?
