### ISSUE TITLE
Draft Exposee

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/dynamic-netsec#4]
TODO: Amr sends an example exposee via E-mail.

An Exposee is 2 page document consisting of:

* Title of your thesis

* 3 paragraphs
  * Introduction + Motivation about the problem statement of your project
  * A high-level comparison with the related work (novelty)
  * A brief description of the outline and scope of the work

* An abstract timeplan (weekly / bi-weekly) regarding the tasks to be accomplished.

**Comment by TjWallas** [comment]
@xiecancn How is the Exposee coming along? Could you please an initial version soon, so I can proof-read it before our meeting tomorrow?

**Comment by xiecancn** [comment]
@TjWallas Still working on it. I got stuck with the paper PSI.  Will send it to you by this evening. Hope you  have time proof-reading it tomorrow morning.

**Comment by TjWallas** [comment]
@xiecancn eaf9950 adds comments to the exposee`. Please consider them and update the exposee` before our next meeting :). Overall, good job so far. Keep pushing forward 👍

**Comment by TjWallas** [comment]
@xiecancn d94bae2 adds a 2nd round of comments to the exposee.

**Comment by TjWallas** [comment]
@xiecancn 6f42616 adds the final round of comments the exposee. Looking good ! Please update this and mark it as the final version.
